platform :ios, '9.0'
inhibit_all_warnings!
use_modular_headers!

target 'Trombi' do
  pod 'RxSwift', '~> 4.4.0'
  pod 'RxCocoa', '~> 4.4.0'
  pod 'SDWebImage', '~> 4.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "#{target.name}"
  end
end
